name: testwebsite
favicon: null
layout_spectrum: 0.7739737557712942
typography_spectrum: 0.9123686903622001
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9468145808205009
  lightness: 0.19673995510675013
  saturation: 0.3306431456003338
  rhythmicContrast: 0.5420141227077693
purpose: []
