name: testwebsite
favicon: null
layout_spectrum: 0.25141
typography_spectrum: 0.32488
title: website TITLE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#14130e'
    - '#656559'
    - '#8e8c80'
    - '#cdc5b2'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
