name: testwebsite
favicon: null
layout_spectrum: 0.25141
typography_spectrum: 0.32488
title: website TITLE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eee8d2'
    - '#161c1c'
    - '#3b523e'
    - '#65767d'
    - '#9f9780'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
